# docker-compose.yml file is used to define the services that make up your app.
# version: '3.9'

services:
  # redis:
  #   container_name: redis
  #   image: redis:7.2.4
  #   restart: always
  #   ports:
  #     - 6379:6379    
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --save 60 1 --loglevel warning

  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    # command: django-admin startproject core .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=test
    restart: always
    depends_on:
      - db
      # - redis

  # worker:
  #   container_name: worker
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/dev/django/Dockerfile
  #   command: celery -A core worker -l INFO
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - todo
  #     - redis
      

    

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    expose:
      - "5432"
    restart: always

  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

  # beat:
  #   container_name: beat
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/dev/django/Dockerfile
  #   command: celery -A core beat -l INFO
  #   volumes:
  #     - ./core:/app
  #   depends_on:
  #     - todo
  #     - redis

  # master:
  #   image: locustio/locust:2.32.7.dev14
  #   ports:
  #    - "8089:8089"
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --master -H http://todo:8000/
  # worker:
  #   image: locustio/locust:2.32.7.dev14
  #   volumes:
  #     - ./core/locust:/mnt/locust
  #   command: -f /mnt/locust/locustfile.py --worker --master-host master
    


volumes:
  postgres_data:
  smtp4dev-data:
  # redis_data:



# Down docker container
# Remove docker images

# OR in terminal :

# terminal command : docker ps -a
# terminal command : docker rm -f <container_id>

# terminal command : docker images
# terminal command : docker rmi -f <image_id> 

# terminal command : docker-compose up --build

# terminal command : docker-compose exec <container_name> sh -c "django-admin startproject core ."
# terminal command : docker-compose exec <container_name> sh -c "python manage.py createsuperuser"

