# docker-compose.yml file is used to define the services that make up your app.
version: '3.8'

services:
  todo:
    container_name: todo
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    # command: django-admin startproject core .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=test
    restart: always
    depends_on:
      - db
    

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    expose:
      - "5432"
    restart: always

volumes:
  postgres_data:


# Down docker container
# Remove docker images

# OR in terminal :

# terminal command : docker ps -a
# terminal command : docker rm -f <container_id>

# terminal command : docker images
# terminal command : docker rmi -f <image_id> 

# terminal command : docker-compose up --build
