name: Django Todo Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: todo_db
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: todo_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U todo_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        while ! pg_isready -h db -p 5432 -U todo_user; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run Tests
      env:
        DATABASE_URL: postgres://todo_user:todo_password@db:5432/todo_db
      run: |
        pytest