name: Django Todo Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      shell: pwsh
      run: |
        Invoke-WebRequest -UseBasicP -Uri "https://get.docker.com" -OutFile "get-docker.ps1"
        & "$PWDget-docker.ps1"

    - name: Install Docker Compose
      shell: pwsh
      run: |
        Invoke-WebRequest -UseBasicP -Uri "https://github.com/docker/compose/releases/latest/download/docker-compose-windows-x86_64.exe" -OutFile "C:Program FilesDockerDocker\resources\bindocker-compose.exe"

    - name: Setup Docker-compose
      shell: pwsh
      run: docker-compose up -d

    - name: Run Tests
      shell: pwsh
      run: docker exec todo sh -c "flake8 && pytest ."