name: Django Todo Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Install Docker
      shell: pwsh
      run: |
        # Enable the WSL feature (Windows Subsystem for Linux)
        dism.exe /Online /Enable-Feature /All /FeatureName:Microsoft-Windows-Subsystem-Linux
        # Install Docker using the Chocolatey package manager
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install docker-desktop -y

    - name: Setup Docker-compose
      shell: pwsh
      run: docker-compose up -d

    - name: Run Tests
      shell: pwsh
      run: docker exec todo sh -c "flake8 && pytest ."