name: Django Todo Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Run Tests
      run: docker exec todo sh -c "pytest ."
