name: Django Todo Project Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: todo_db
          POSTGRES_USER: todo_user
          POSTGRES_PASSWORD: todo_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U todo_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Start Services
      run: |
        docker-compose -f F://Git-Repository//Todo-App-Project-CBV//docker-compose.yml up -d

    - name: Run Tests
      run: |
        docker exec todo sh -c "flake8 && pytest ."